Endpoints:
  DatasetHandler:
    Host: "localhost"
    Port: 50051
Auth:
  URL: "https://keycloak.m1.k8s.computational.bio/auth/realms/NFDI4Biodiversity"
  CallbackURL: "http://localhost:9050/auth/callback"
  ClientID: "core-server-test"
  AuthURL: "https://keycloak.m1.k8s.computational.bio/auth/realms/NFDI4Biodiversity/protocol/openid-connect/auth"
  TokenURL: "https://keycloak.m1.k8s.computational.bio/auth/realms/NFDI4Biodiversity/protocol/openid-connect/token"
  UserInfoURL: "https://keycloak.m1.k8s.computational.bio/auth/realms/NFDI4Biodiversity/protocol/openid-connect/userinfo"