Endpoints:
  DatasetHandler:
    Host: "biodatadbapi"
    Port: 9000
Auth:
  URL: "https://keycloak.infra.ingress.rancher.computational.bio/auth/realms/BioDataDB"
  CallbackURL: "https://ui.biodatadb.ingress.rancher2.computational.bio/auth/callback"
  ClientID: "BioDataDB"
  AuthURL: "https://keycloak.infra.ingress.rancher.computational.bio/auth/realms/BioDataDB/protocol/openid-connect/auth"
  TokenURL: "https://keycloak.infra.ingress.rancher.computational.bio/auth/realms/BioDataDB/protocol/openid-connect/token"
  UserInfoURL: "https://keycloak.infra.ingress.rancher.computational.bio/auth/realms/BioDataDB/protocol/openid-connect/userinfo"