Endpoints:
  DatasetHandler:
    Host: "core-server"
    Port: 9000
Auth:
  URL: "https://keycloak.m1.k8s.computational.bio/auth/realms/SciObjsDB"
  CallbackURL: "https://website.core-server-dev.m1.k8s.computational.bio//auth/callback"
  ClientID: "core-server-website"
  AuthURL: "https://keycloak.m1.k8s.computational.bio/auth/realms/SciObjsDB/protocol/openid-connect/auth"
  TokenURL: "https://keycloak.m1.k8s.computational.bio/auth/realms/SciObjsDB/protocol/openid-connect/token"
  UserInfoURL: "https://keycloak.m1.k8s.computational.bio/auth/realms/SciObjsDB/protocol/openid-connect/userinfo"